name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: write
      pull-requests: write
      actions: write
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Get repository information
      run: |
        # Use the `github_token` to get repository information
        # For example, get the list of pull requests:
        curl -X POST -vvv -H 'Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' -H 'content-type: application/json' https://api.github.com/repos/mohamedaymenkarmous/WebGoat/sast_scan.yml/dispatches -d '{"event_type":"test,"client_payload":{"unit":false,"integration":true}}'

